$(".bnl").delay(3000).fadeOut("slow");
$(".menu").delay(5000).fadeIn("slow");
$(".name").delay(5000).fadeIn("slow");
$(".director").delay(5000).fadeIn("slow");
$("li").mouseover(function(){
    $(this).addClass("selected");
})
$("li").mouseleave(function(){
    $(this).removeClass("selected");
})
